language: ruby
rvm:
  - 2.6.3
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

addons:
  apt:
    packages:
    - libcurl4-openssl-dev
install:
  - sudo apt-get install graphviz
cache: bundler # caching bundler gem packages will speed up build

script:
  - bundle
  - bundle exec jekyll build
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: _site
  target_branch: master
  on:
    branch: source
# Optional: disable email notifications about the outcome of your builds
notifications:
  email: false