name: Jekyll Deploy

on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ source ]
  workflow_dispatch:
jobs:
  jekyll:
    runs-on: ubuntu-16.04
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-ruby@v1
      with:
        ruby-version: '2.6' # Version range or exact version of a Ruby version to use, using semvers version range syntax.
    - uses: actions/setup-java@v2
      with:
        distribution: 'adopt' # See 'Supported distributions' for available options
        java-version: '11'
    - name: Install packages
      run: sudo apt-get install libcurl4-openssl-dev graphviz
    # Use GitHub Actions' cache to shorten build times and decrease load on servers
    - uses: actions/cache@v2
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile') }}
        restore-keys: |
          ${{ runner.os }}-gems-
    - name: Build site
      run: |
        gem install bundler
        bundle
        bundle exec jekyll build

