name: Jekyll Deploy

on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ source ]
  workflow_dispatch:
jobs: 
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install packages
        run: sudo apt-get install libcurl4-openssl-dev graphviz
      - name: Install Gem Dependency
        run: bundle
      - name: Build & Deploy to GitHub Pages
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ secrets.GITHUB_REPOSITORY }}
          GITHUB_ACTOR: ${{ secrets.GITHUB_ACTOR }}
        uses: BryanSchuetz/jekyll-deploy-gh-pages@v2.0
